# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_unit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='Image',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
