# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_paragraph_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
