# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_paragraph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='AlignLeft',
            field=models.NullBooleanField(),
        ),
    ]
