# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_paragraph_alignleft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('watsup', models.NullBooleanField()),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Unit')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
