# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20160813_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='AlphabetOrder',
            field=models.NullBooleanField(),
        ),
    ]
