# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_getintouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='TransportFlag',
            field=models.NullBooleanField(),
        ),
    ]
