# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_transportorder_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='Eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
