# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_unit_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrderModerated',
            },
        ),
        migrations.CreateModel(
            name='OrderModeratedGetInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GetInTouch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GetInTouch')),
                ('OrderModerated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderModerated')),
            ],
            options={
                'db_table': 'OrderModeratedGetInTouch',
            },
        ),
        migrations.CreateModel(
            name='OrderModeratedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order')),
                ('OrderModerated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderModerated')),
            ],
            options={
                'db_table': 'OrderModeratedOrder',
            },
        ),
        migrations.CreateModel(
            name='OrderModeratedParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderModerated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderModerated')),
                ('Paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Paragraph')),
            ],
            options={
                'db_table': 'OrderModeratedParagraph',
            },
        ),
        migrations.CreateModel(
            name='OrderModeratedTransportOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderModerated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderModerated')),
                ('TransportOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.TransportOrder')),
            ],
            options={
                'db_table': 'OrderModeratedTransportOrder',
            },
        ),
        migrations.CreateModel(
            name='OrderModeratedUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderModerated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderModerated')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Unit')),
            ],
            options={
                'db_table': 'OrderModeratedUnit',
            },
        ),
    ]
