# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_ordermoderated_ordermoderatedgetintouch_ordermoderatedorder_ordermoderatedparagraph_ordermoderatedtr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
