# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20160923_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
