# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20160923_1101'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerorder',
            table='CustomerOrder',
        ),
    ]
