# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20160923_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransportOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order')),
            ],
            options={
                'db_table': 'CustomerTransportOrder',
            },
        ),
        migrations.AddField(
            model_name='transportorder',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='DeliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
