# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20160924_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorder',
            name='Text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
