# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_transportorder_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermoderated',
            name='From',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermoderated',
            name='To',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
