# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20160924_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='Volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
