# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20160924_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransportorder',
            name='Order',
        ),
        migrations.AddField(
            model_name='customertransportorder',
            name='TransportOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TransportOrder'),
        ),
        migrations.AlterField(
            model_name='customertransportorder',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer'),
        ),
    ]
