# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_customergetintouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='getintouch',
            name='DeliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
