# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20160926_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Keyword',
            new_name='KeyWord',
        ),
    ]
