# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_article_ownerurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='HexColor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
