# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_paragraph_hexcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='CanBuyInCubes',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='unit',
            name='CanLoadUnload',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='unit',
            name='DeliveryInRegion',
            field=models.NullBooleanField(),
        ),
    ]
