# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20161008_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('OwnerUrl', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Unit')),
            ],
            options={
                'db_table': 'KeyWord',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='KeyWord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.KeyWord'),
        ),
    ]
