# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20161008_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='CanBuyInCubes',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='CanLoadUnload',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='DeliveryInRegion',
        ),
    ]
